
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analisishtml;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150930 (SVN rev 66) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserh extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserh() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserh(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserh(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\002\010\000\002\006" +
    "\007\000\002\006\002\000\002\007\007\000\002\010\007" +
    "\000\002\010\002\000\002\014\004\000\002\011\007\000" +
    "\002\012\006\000\002\012\002\000\002\013\005\000\002" +
    "\013\005\000\002\013\002\000\002\005\006\000\002\005" +
    "\006\000\002\005\006\000\002\005\006\000\002\005\002" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\003" +
    "\003\000\002\003\003\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\042\004\001\002\000\014\023\uffef\126" +
    "\007\127\011\130\013\131\010\001\002\000\004\002\006" +
    "\001\002\000\004\002\001\001\002\000\004\025\077\001" +
    "\002\000\004\025\074\001\002\000\004\025\071\001\002" +
    "\000\004\023\025\001\002\000\004\025\014\001\002\000" +
    "\016\003\017\116\023\117\015\120\021\123\022\125\020" +
    "\001\002\000\016\023\uffec\065\uffec\126\uffec\127\uffec\130" +
    "\uffec\131\uffec\001\002\000\014\023\uffef\126\007\127\011" +
    "\130\013\131\010\001\002\000\016\023\uffe9\065\uffe9\126" +
    "\uffe9\127\uffe9\130\uffe9\131\uffe9\001\002\000\016\023\uffea" +
    "\065\uffea\126\uffea\127\uffea\130\uffea\131\uffea\001\002\000" +
    "\016\023\uffed\065\uffed\126\uffed\127\uffed\130\uffed\131\uffed" +
    "\001\002\000\016\023\uffeb\065\uffeb\126\uffeb\127\uffeb\130" +
    "\uffeb\131\uffeb\001\002\000\016\023\uffee\065\uffee\126\uffee" +
    "\127\uffee\130\uffee\131\uffee\001\002\000\004\023\ufff1\001" +
    "\002\000\006\044\027\046\ufffe\001\002\000\004\046\041" +
    "\001\002\000\014\023\uffef\126\007\127\011\130\013\131" +
    "\010\001\002\000\004\023\031\001\002\000\006\045\ufffb" +
    "\064\033\001\002\000\004\045\040\001\002\000\014\023" +
    "\uffef\126\007\127\011\130\013\131\010\001\002\000\004" +
    "\023\035\001\002\000\016\003\017\116\023\117\015\120" +
    "\021\123\022\125\020\001\002\000\004\065\037\001\002" +
    "\000\004\045\ufffc\001\002\000\004\046\uffff\001\002\000" +
    "\014\023\uffef\126\007\127\011\130\013\131\010\001\002" +
    "\000\004\043\043\001\002\000\004\002\000\001\002\000" +
    "\004\023\045\001\002\000\004\066\046\001\002\000\014" +
    "\023\uffef\126\007\127\011\130\013\131\010\001\002\000" +
    "\004\047\052\001\002\000\004\066\046\001\002\000\004" +
    "\047\ufffa\001\002\000\004\043\ufffd\001\002\000\004\023" +
    "\054\001\002\000\006\067\ufff7\074\056\001\002\000\004" +
    "\067\070\001\002\000\010\070\057\072\061\075\ufff4\001" +
    "\002\000\004\072\066\001\002\000\004\075\064\001\002" +
    "\000\004\073\062\001\002\000\010\070\057\072\061\075" +
    "\ufff4\001\002\000\004\075\ufff6\001\002\000\006\067\ufff7" +
    "\074\056\001\002\000\004\067\ufff8\001\002\000\010\070" +
    "\057\072\061\075\ufff4\001\002\000\004\075\ufff5\001\002" +
    "\000\004\066\ufff9\001\002\000\016\003\017\116\023\117" +
    "\015\120\021\123\022\125\020\001\002\000\014\023\uffef" +
    "\126\007\127\011\130\013\131\010\001\002\000\004\023" +
    "\ufff2\001\002\000\016\003\017\116\023\117\015\120\021" +
    "\123\022\125\020\001\002\000\014\023\uffef\126\007\127" +
    "\011\130\013\131\010\001\002\000\004\023\ufff0\001\002" +
    "\000\016\003\017\116\023\117\015\120\021\123\022\125" +
    "\020\001\002\000\014\023\uffef\126\007\127\011\130\013" +
    "\131\010\001\002\000\004\023\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\002\004\001\001\000\004\005\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\015\001\001\000\002\001\001" +
    "\000\004\005\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\025\001\001\000\004\007" +
    "\041\001\001\000\004\005\027\001\001\000\002\001\001" +
    "\000\004\010\031\001\001\000\002\001\001\000\004\005" +
    "\033\001\001\000\002\001\001\000\004\004\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\047\014\046\001\001\000" +
    "\004\005\052\001\001\000\002\001\001\000\006\011\047" +
    "\014\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\012\054\001\001\000\002\001\001" +
    "\000\004\013\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\062\001\001\000\002" +
    "\001\001\000\004\012\064\001\001\000\002\001\001\000" +
    "\004\013\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\071\001\001\000\004\005\072\001\001\000" +
    "\002\001\001\000\004\004\074\001\001\000\004\005\075" +
    "\001\001\000\002\001\001\000\004\004\077\001\001\000" +
    "\004\005\100\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserh$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserh$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserh$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


//Codigo visible
    public String ER="";
    public String EN="";
    public int id = 0;
    public void syntax_error(Symbol s){
        System.out.println("Error R de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) +" " + s.value);
        
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error NR de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserh$actions {

//Codigo de usuario
    String tmp="";
    String id1 = "";
    String id2 = "";
    int x1;
    int x2;
    int y1, y2;
    int x = 0;
    int y = 0;

  private final parserh parser;

  /** Constructor */
  CUP$parserh$actions(parserh parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserh$do_action_part00000000(
    int                        CUP$parserh$act_num,
    java_cup.runtime.lr_parser CUP$parserh$parser,
    java.util.Stack            CUP$parserh$stack,
    int                        CUP$parserh$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserh$result;

      /* select the action based on the action number */
      switch (CUP$parserh$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$parserh$stack.elementAt(CUP$parserh$top-1)).value;
		RESULT = start_val;
              CUP$parserh$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-1)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserh$parser.done_parsing();
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= HTML_I ATRIB MAYOR ENCABE CUERPO HTML_F 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-5)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ENCABE ::= HEAD_I ATRIB MAYOR TITULO HEAD_F 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ENCABE",4, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-4)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ENCABE ::= 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ENCABE",4, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CUERPO ::= BODY_I ATRIB MAYOR VARIOS BODY_F 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("CUERPO",5, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-4)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // TITULO ::= TITLE_I ATRIB MAYOR VALORES TITLE_F 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TITULO",6, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-4)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // TITULO ::= 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TITULO",6, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VARIOS ::= TABLA VARIOS 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VARIOS",10, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-1)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TABLA ::= TABLE_I ATRIB MAYOR PROPTA TABLE_F 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TABLA",7, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-4)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // PROPTA ::= TR_I PROPT2 TR_F PROPTA 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("PROPTA",8, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-3)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // PROPTA ::= 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("PROPTA",8, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // PROPT2 ::= TD_I TD_F PROPT2 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("PROPT2",9, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-2)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // PROPT2 ::= TH_I TD_I PROPT2 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("PROPT2",9, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-2)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // PROPT2 ::= 
            {
              Object RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("PROPT2",9, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ATRIB ::= COLOR IGUAL VALORES ATRIB 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-3)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ATRIB ::= TCOLOR IGUAL VALORES ATRIB 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-3)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ATRIB ::= ALIGN IGUAL VALORES ATRIB 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-3)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ATRIB ::= FONT IGUAL VALORES ATRIB 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserh$stack.elementAt(CUP$parserh$top-3)), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ATRIB ::= 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // VALORES ::= ENTERO 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // VALORES ::= DECIMAL 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // VALORES ::= ID 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // VALORES ::= CADENA 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // VALORES ::= CADENA2 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // VALORES ::= error 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("VALORES",2, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // TIPO ::= INT 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // TIPO ::= BOOLEA 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // TIPO ::= STRIN 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // TIPO ::= CARAC 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // TIPO ::= DOUBL 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // TIPO ::= error 
            {
              String RESULT =null;

              CUP$parserh$result = parser.getSymbolFactory().newSymbol("TIPO",1, ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserh$stack.peek()), RESULT);
            }
          return CUP$parserh$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserh$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserh$do_action(
    int                        CUP$parserh$act_num,
    java_cup.runtime.lr_parser CUP$parserh$parser,
    java.util.Stack            CUP$parserh$stack,
    int                        CUP$parserh$top)
    throws java.lang.Exception
    {
              return CUP$parserh$do_action_part00000000(
                               CUP$parserh$act_num,
                               CUP$parserh$parser,
                               CUP$parserh$stack,
                               CUP$parserh$top);
    }
}

}
