
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analisisjson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPU = 7;
  public static final int CARAC = 11;
  public static final int BOOLEA = 9;
  public static final int CADENA = 28;
  public static final int INT = 8;
  public static final int DECIMAL = 25;
  public static final int LLAV_C = 3;
  public static final int LLAV_A = 2;
  public static final int STRIN = 10;
  public static final int COR_C = 5;
  public static final int ENTER = 27;
  public static final int ID = 24;
  public static final int CLASE = 18;
  public static final int SPACE = 26;
  public static final int COR_A = 4;
  public static final int CONT = 29;
  public static final int TIPO = 15;
  public static final int COMA = 6;
  public static final int NOMBRE = 19;
  public static final int EOF = 0;
  public static final int OBJEC = 13;
  public static final int DOUBL = 12;
  public static final int PARAME = 22;
  public static final int TEXTO = 21;
  public static final int COMENT = 20;
  public static final int error = 1;
  public static final int CLASES = 16;
  public static final int ENTERO = 23;
  public static final int VARIAB = 17;
  public static final int VOID = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAV_A",
  "LLAV_C",
  "COR_A",
  "COR_C",
  "COMA",
  "DOSPU",
  "INT",
  "BOOLEA",
  "STRIN",
  "CARAC",
  "DOUBL",
  "OBJEC",
  "VOID",
  "TIPO",
  "CLASES",
  "VARIAB",
  "CLASE",
  "NOMBRE",
  "COMENT",
  "TEXTO",
  "PARAME",
  "ENTERO",
  "ID",
  "DECIMAL",
  "SPACE",
  "ENTER",
  "CADENA",
  "CONT"
  };
}

